### ISSUE TITLE
about val_iteration

### ISSUE THREAD

**Issue by vv123-star** [Prasanna1991/LatentMixing#2]
set val_iteration=250 batchsize=64 , but the len(datasetTrainLabeled)=7311, len(datasetTrainUnLabelled)=96512, this can cover full labeled dataset and unlabeled dataset when training? Thanks for your time.

**Comment by Prasanna1991** [comment]
Hi,

In one epoch, it won't cover the whole dataset, especially the unlabeled dataset. This was an intentional choice to balance samples from labeled and unlabeled sets in each epoch. Over total epochs, we expect to cover the unlabeled dataset.

I hope this helps.
